%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%% This matlab script plot two scatter graphs of global fossil fuel CO2 emission in one figure with different
%% indices.
%% 绘制全球化石燃料CO2排放的不同指标散点图
%%      *排放数据源为CDIAC和EDGAR
%%      *CDIAC时间序列为1751-2014
%%      *EDGAR时间序列为1970-2016
%%      *单位GDP排放量已做对数处理
%% ****注意：
%%      该脚本写法采用Matlab 2014b以后版本推荐的引用对象写法。该版本之前的Matlab将无法运行此脚本。
%%      若需在较低版本Matlab运行，请重写各个子图的标注部分为set()函数格式。
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%% clean various and existed figures
close all
clear all
clc

%% load data from file
load('historical_per.mat')
figure

%% CDIAC per_capita
per_capita_ax = subplot(2,1,1);
hold on
% draw CDIAC scatter graph(per capita)
scatter_CDIAC_per_capita = scatter(per_capita_ax,...
                                    CDIAC_year,...
                                    CDIAC_per_capita,...
                                    sz,[0,0.4470,0.7410],...
                                    'filled');
% draw CDIAC line graph(per capita mean)
line_CDIAC_per_capita_mean = plot(per_capita_ax,...
                                  CDIAC_year_1950_2016,...
                                  CDIAC_per_capita_mean,...
                                  'LineWidth',2,...
                                  'Color',[0.8500,0.3250,0.0980]);
% draw EDGAR scatter graph(per capita)
scatter_EDGAR_per_capita = scatter(per_capita_ax,...
                                    EDGAR_year,...
                                    EDGAR_per_capita,...
                                    sz,[0.9290,0.6940,0.1250],...
                                    'filled');
% draw EDGAR line graph(per capita mean)
line_EDGAR_per_capita_mean = plot(per_capita_ax,...
                                  EDGAR_year_1970_2016,...
                                  EDGAR_per_capita_mean,...
                                  'LineWidth',2,...
                                  'Color', [0.4940,0.1840,0.5560]);
%% per capita lables setting
per_capita_ax.YLim = [0 50];
per_capita_ax.YTick = [0:10:50];
per_capita_ax.XLim = [1949 2017];
per_capita_ax.XTick = [1950:5:2015];
per_capita_ax.TickDir = 'out';
per_capita_ax.YGrid = 'on';
legend(per_capita_ax,...
        'CDIAC per capita emission',...
        'CDIAC per capita global mean emission',...
        'EDGAR per capita emission',...
        'EDGAR per capita global mean emission',...
        'Location','best');
per_capita_ax.YLabel = ylabel('C /kt C');
per_capita_ax.XLabel = xlabel('Year');
per_capita_ax.Title = title(per_capita_ax,...
                            {'Nations and Global per capita',...
                            ' CO_{2} Emission from Fossil Fuel'});
hold off

%% EDGAR per dollar
per_dollar_ax = subplot(2,1,2);
hold on
% draw EDGAR scatter graph(per dollar)
scatter_EDGAR_per_dollar = scatter(per_dollar_ax,...
                                     EDGAR_year_2,...
                                     EDGAR_per_dollar_lg,...
                                     sz,...
                                     'filled');
% draw EDGAR line graph(per dollar)
line_EDGAR_per_dollar_mean = plot(per_dollar_ax,...
                                    EDGAR_year_2_1970_2016,...
                                    EDGAR_per_dollar_mean_lg,...
                                    'LineWidth',2);
% set labels
per_dollar_ax.YLim = [-4.5 3];
per_dollar_ax.YTick = [-4:1:3];
per_dollar_ax.XLim = [1969 2017];
per_dollar_ax.XTick = [1970:5:2015];
per_dollar_ax.TickDir = 'out';
per_dollar_ax.YGrid = 'on';
legend(per_dollar_ax,...
        'emission',...
        'global mean emission',...
        'Location','best',...
        'Orientation','horizontal');
per_dollar_ax.YLabel = ylabel('log_{10}(C) /kt C');
per_dollar_ax.XLabel = xlabel('Year');
per_dollar_ax.Title = title(per_dollar_ax,...
                            {'EDGAR Nations and Global per 1,000 USD GDP',...
                            'CO_{2} Emission from Fossil Fuel'});
hold off