CREATE TABLE countries.countries_index(
    ISO TEXT,
    NAME_ISO TEXT,
    NAME_ENGLI TEXT,
    NAME_EDIGA_DATASET TEXT,
    NAME_CDICA_COUNTRY_CODES INT,
    NAME_FAO TEXT,
    NAME_LOCAL TEXT,
    NAME_CHINE TEXT,
    SOVEREIGN TEXT,
    ISO2 TEXT,
    FIPS TEXT,
    ISON INT,
    UNREGION1 TEXT,
    UNREGION2 TEXT
);
